print('{:=^30}'.format(' DESAFIO 012 '))
preco = float(input('Qual é o preço do produto? R$'))
desconto = preco * (1 - 0.05)
print('Preço com desconto de 5% é R${:.2f}'.format(desconto))
print('=' * 30)
