print('========== DESAFIO 004 ==========')
n = input('Digite algo: ')
print(n)
print('Alfanúmerio:', n.isalnum())
print('Alfabético:', n.isalpha())
print('Maiúsculo:', n.isupper())
print('Minúsculo:', n.islower())
print('Numérico:', n.isnumeric())
print('Real:', n.isdecimal())
print('=================================')
